<a href="https://colab.research.google.com/github/remisoulignac/mit_scm_python/blob/main/SC0X_Python_Samples.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
!pip install ortools

     |████████████████████████████████| 15.5 MB 5.4 MB/s 
     |████████████████████████████████| 1.0 MB 50.4 MB/s 
  Attempting uninstall: protobuf
    Found existing installation: protobuf 3.17.3
    Uninstalling protobuf-3.17.3:
      Successfully uninstalled protobuf-3.17.3
ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts.
tensorflow 2.8.0 requires tf-estimator-nightly==2.8.0.dev2021122109, which is not installed.


In [2]:
"""Simple travelling salesman problem on a circuit board."""

from __future__ import print_function
import math
from ortools.constraint_solver import routing_enums_pb2
from ortools.constraint_solver import pywrapcp


def create_data_model():
    """Stores the data for the problem : (X,Y) of each node."""
    data = {}
    # Locations in block units
    data['locations'] = [
        (288, 149), (288, 129), (270, 133), (256, 141), (256, 157), (246, 157),
        (236, 169), (228, 169), (228, 161), (220, 169), (212, 169), (204, 169),
        (196, 169), (188, 169), (196, 161), (188, 145), (172, 145), (164, 145),
        (156, 145), (148, 145), (140, 145), (148, 169), (164, 169), (172, 169),
        (156, 169), (140, 169), (132, 169), (124, 169), (116, 161), (104, 153),
        (104, 161), (104, 169), (90, 165), (80, 157), (64, 157), (64, 165),
        (56, 169), (56, 161), (56, 153), (56, 145), (56, 137), (56, 129),
        (56, 121), (40, 121), (40, 129), (40, 137), (40, 145), (40, 153),
        (40, 161), (40, 169), (32, 169), (32, 161), (32, 153), (32, 145),
        (32, 137), (32, 129), (32, 121), (32, 113), (40, 113), (56, 113),
        (56, 105), (48, 99), (40, 99), (32, 97), (32, 89), (24, 89),
        (16, 97), (16, 109), (8, 109), (8, 97), (8, 89), (8, 81),
        (8, 73), (8, 65), (8, 57), (16, 57), (8, 49), (8, 41),
        (24, 45), (32, 41), (32, 49), (32, 57), (32, 65), (32, 73),
        (32, 81), (40, 83), (40, 73), (40, 63), (40, 51), (44, 43),
        (44, 35), (44, 27), (32, 25), (24, 25), (16, 25), (16, 17),
        (24, 17), (32, 17), (44, 11), (56, 9), (56, 17), (56, 25),
        (56, 33), (56, 41), (64, 41), (72, 41), (72, 49), (56, 49),
        (48, 51), (56, 57), (56, 65), (48, 63), (48, 73), (56, 73),
        (56, 81), (48, 83), (56, 89), (56, 97), (104, 97), (104, 105),
        (104, 113), (104, 121), (104, 129), (104, 137), (104, 145), (116, 145),
        (124, 145), (132, 145), (132, 137), (140, 137), (148, 137), (156, 137),
        (164, 137), (172, 125), (172, 117), (172, 109), (172, 101), (172, 93),
        (172, 85), (180, 85), (180, 77), (180, 69), (180, 61), (180, 53),
        (172, 53), (172, 61), (172, 69), (172, 77), (164, 81), (148, 85),
        (124, 85), (124, 93), (124, 109), (124, 125), (124, 117), (124, 101),
        (104, 89), (104, 81), (104, 73), (104, 65), (104, 49), (104, 41),
        (104, 33), (104, 25), (104, 17), (92, 9), (80, 9), (72, 9),
        (64, 21), (72, 25), (80, 25), (80, 25), (80, 41), (88, 49),
        (104, 57), (124, 69), (124, 77), (132, 81), (140, 65), (132, 61),
        (124, 61), (124, 53), (124, 45), (124, 37), (124, 29), (132, 21),
        (124, 21), (120, 9), (128, 9), (136, 9), (148, 9), (162, 9),
        (156, 25), (172, 21), (180, 21), (180, 29), (172, 29), (172, 37),
        (172, 45), (180, 45), (180, 37), (188, 41), (196, 49), (204, 57),
        (212, 65), (220, 73), (228, 69), (228, 77), (236, 77), (236, 69),
        (236, 61), (228, 61), (228, 53), (236, 53), (236, 45), (228, 45),
        (228, 37), (236, 37), (236, 29), (228, 29), (228, 21), (236, 21),
        (252, 21), (260, 29), (260, 37), (260, 45), (260, 53), (260, 61),
        (260, 69), (260, 77), (276, 77), (276, 69), (276, 61), (276, 53),
        (284, 53), (284, 61), (284, 69), (284, 77), (284, 85), (284, 93),
        (284, 101), (288, 109), (280, 109), (276, 101), (276, 93), (276, 85),
        (268, 97), (260, 109), (252, 101), (260, 93), (260, 85), (236, 85),
        (228, 85), (228, 93), (236, 93), (236, 101), (228, 101), (228, 109),
        (228, 117), (228, 125), (220, 125), (212, 117), (204, 109), (196, 101),
        (188, 93), (180, 93), (180, 101), (180, 109), (180, 117), (180, 125),
        (196, 145), (204, 145), (212, 145), (220, 145), (228, 145), (236, 145),
        (246, 141), (252, 125), (260, 129), (280, 133)
    ] 
    data['num_vehicles'] = 1
    data['depot'] = 0
    return data


def compute_euclidean_distance_matrix(locations):
    """Creates callback to return distance between points."""
    distances = {}
    for from_counter, from_node in enumerate(locations):
        distances[from_counter] = {}
        for to_counter, to_node in enumerate(locations):
            if from_counter == to_counter:
                distances[from_counter][to_counter] = 0
            else:
                # Euclidean distance
                distances[from_counter][to_counter] = (int(
                    math.hypot((from_node[0] - to_node[0]),
                               (from_node[1] - to_node[1]))))
    return distances


def print_solution(manager, routing, solution):
    """Prints solution on console."""
    print('Objective: {}'.format(solution.ObjectiveValue()))
    index = routing.Start(0)
    plan_output = 'Route:\n'
    route_distance = 0
    while not routing.IsEnd(index):
        plan_output += ' {} ->'.format(manager.IndexToNode(index))
        previous_index = index
        index = solution.Value(routing.NextVar(index))
        route_distance += routing.GetArcCostForVehicle(previous_index, index, 0)
    plan_output += ' {}\n'.format(manager.IndexToNode(index))
    print(plan_output)
    plan_output += 'Objective: {}m\n'.format(route_distance)

data = create_data_model()

# Create the routing index manager.
manager = pywrapcp.RoutingIndexManager(len(data['locations']),
                                        data['num_vehicles'], data['depot'])

# Create Routing Model.
routing = pywrapcp.RoutingModel(manager)

distance_matrix = compute_euclidean_distance_matrix(data['locations'])

def distance_callback(from_index, to_index):
    """Returns the distance between the two nodes."""
    # Convert from routing variable Index to distance matrix NodeIndex.
    from_node = manager.IndexToNode(from_index)
    to_node = manager.IndexToNode(to_index)
    return distance_matrix[from_node][to_node]

transit_callback_index = routing.RegisterTransitCallback(distance_callback)

# Define cost of each arc.
routing.SetArcCostEvaluatorOfAllVehicles(transit_callback_index)

# Setting first solution heuristic.
search_parameters = pywrapcp.DefaultRoutingSearchParameters()
search_parameters.first_solution_strategy = (
    routing_enums_pb2.FirstSolutionStrategy.PATH_CHEAPEST_ARC)

# Solve the problem.
solution = routing.SolveWithParameters(search_parameters)

# Print solution on console.
if solution:
    print_solution(manager, routing, solution)

Objective: 2790
Route:
 0 -> 1 -> 279 -> 2 -> 278 -> 277 -> 248 -> 247 -> 243 -> 242 -> 241 -> 240 -> 239 -> 238 -> 245 -> 244 -> 246 -> 249 -> 250 -> 229 -> 228 -> 231 -> 230 -> 237 -> 236 -> 235 -> 234 -> 233 -> 232 -> 227 -> 226 -> 225 -> 224 -> 223 -> 222 -> 218 -> 221 -> 220 -> 219 -> 202 -> 203 -> 204 -> 205 -> 207 -> 206 -> 211 -> 212 -> 215 -> 216 -> 217 -> 214 -> 213 -> 210 -> 209 -> 208 -> 251 -> 254 -> 255 -> 257 -> 256 -> 253 -> 252 -> 139 -> 140 -> 141 -> 142 -> 143 -> 199 -> 201 -> 200 -> 195 -> 194 -> 193 -> 191 -> 190 -> 189 -> 188 -> 187 -> 163 -> 164 -> 165 -> 166 -> 167 -> 168 -> 169 -> 171 -> 170 -> 172 -> 105 -> 106 -> 104 -> 103 -> 107 -> 109 -> 110 -> 113 -> 114 -> 116 -> 117 -> 61 -> 62 -> 63 -> 65 -> 64 -> 84 -> 85 -> 115 -> 112 -> 86 -> 83 -> 82 -> 87 -> 111 -> 108 -> 89 -> 90 -> 91 -> 102 -> 101 -> 100 -> 99 -> 98 -> 97 -> 96 -> 95 -> 94 -> 93 -> 92 -> 79 -> 88 -> 81 -> 80 -> 78 -> 77 -> 76 -> 74 -> 75 -> 73 -> 72 -> 71 -> 70 -> 69 -> 66 -> 68 -> 67 -> 57 -> 

In [3]:
#finding shortest path in a graph

import numpy as np
from __future__ import print_function
import math, sys
from ortools.constraint_solver import routing_enums_pb2
from ortools.constraint_solver import pywrapcp
np.set_printoptions(suppress=True,linewidth=sys.maxsize,threshold=sys.maxsize)


inf=-1
distances=np.array([
# [ "CH", "CL", "HB", "SL", "IN", "CO", "MT", "WA", "CI", "CN", "RI", "LV", "LX", "NV", "KV", "GR" ]
  [ 000,  362,  inf,  300,  201,  inf,  inf,  inf,  inf,  inf,  inf,  inf,  inf,  inf,  inf,  inf  ], #CH
  [ inf,  000,  332,  inf,  inf,  142,  201,  inf,  inf,  251,  inf,  inf,  inf,  inf,  inf,  inf  ], #CL
  [ inf,  inf,  000,  inf,  inf,  inf,  213,  120,  inf,  inf,  inf,  inf,  inf,  inf,  inf,  inf  ], #HB
  [ inf,  inf,  inf,  000,  245,  inf,  inf,  inf,  inf,  inf,  inf,  263,  inf,  312,  inf,  inf  ], #SL
  [ inf,  inf,  inf,  inf,  000,  176,  inf,  inf,  112,  inf,  inf,  114,  inf,  inf,  inf,  inf  ], #IN
  [ inf,  inf,  inf,  inf,  inf,  000,  inf,  inf,  105,  inf,  inf,  inf,  inf,  inf,  inf,  inf  ], #CO
  [ inf,  inf,  inf,  inf,  inf,  inf,  000,  209,  inf,  157,  inf,  inf,  inf,  inf,  inf,  inf  ], #MT
  [ inf,  inf,  inf,  inf,  inf,  inf,  inf,  000,  inf,  inf,  111,  inf,  inf,  inf,  inf,  inf  ], #WA
  [ inf,  inf,  inf,  inf,  inf,  inf,  inf,  inf,  000,  204,  inf,  inf,   95,  inf,  inf,  inf  ], #CI
  [ inf,  inf,  inf,  inf,  inf,  inf,  inf,  inf,  inf,  000,  318,  inf,  177,  inf,  inf,  244  ], #CN
  [ inf,  inf,  inf,  inf,  inf,  inf,  inf,  inf,  inf,  inf,  000,  inf,  inf,  inf,  inf,  205  ], #RI
  [ inf,  inf,  inf,  inf,  inf,  inf,  inf,  inf,  inf,  inf,  inf,  000,   86,  175,  inf,  inf  ], #LV
  [ inf,  inf,  inf,  inf,  inf,  inf,  inf,  inf,  inf,  inf,  inf,  inf,  000,  inf,  170,  inf  ], #LX
  [ inf,  inf,  inf,  inf,  inf,  inf,  inf,  inf,  inf,  inf,  inf,  inf,  inf,  000,  180,  inf  ], #NV
  [ inf,  inf,  inf,  inf,  inf,  inf,  inf,  inf,  inf,  inf,  inf,  inf,  inf,  inf,  000,  299  ], #KV
  [ inf,  inf,  inf,  inf,  inf,  inf,  inf,  inf,  inf,  inf,  inf,  inf,  inf,  inf,  inf,  000  ]  #GR
])

triinf=np.tril_indices(distances.shape[0], -1)
distances[triinf] = distances.T[triinf] #https://stackoverflow.com/questions/16444930/copy-upper-triangle-to-lower-triangle-in-a-python-matrix
print(distances)


def print_solution(manager, routing, solution):
    """Prints solution on console."""
    print('Objective: {}'.format(solution.ObjectiveValue()))
    index = routing.Start(0)
    plan_output = 'Route:\n'
    route_distance = 0
    while not routing.IsEnd(index):
        plan_output += ' {} ->'.format(manager.IndexToNode(index))
        previous_index = index
        index = solution.Value(routing.NextVar(index))
        route_distance += routing.GetArcCostForVehicle(previous_index, index, 0)
    plan_output += ' {}\n'.format(manager.IndexToNode(index))
    print(plan_output)
    plan_output += 'Objective: {}m\n'.format(route_distance)


# Create the routing index manager.
manager = pywrapcp.RoutingIndexManager(distances.shape[0],
                                        1, 1)

# Create Routing Model.
routing = pywrapcp.RoutingModel(manager)

def distance_callback(from_index, to_index):
    """Returns the distance between the two nodes."""
    # Convert from routing variable Index to distance matrix NodeIndex.
    from_node = manager.IndexToNode(from_index)
    to_node = manager.IndexToNode(to_index)
    return distances[from_node][to_node]

transit_callback_index = routing.RegisterTransitCallback(distance_callback)

# Define cost of each arc.
routing.SetArcCostEvaluatorOfAllVehicles(transit_callback_index)

# Setting first solution heuristic.
search_parameters = pywrapcp.DefaultRoutingSearchParameters()
#results with AUTOMATIC, LOCAL_CHEAPEST_ARC, PATH_CHEAPEST_ARC, PATH_MOST_CONSTRAINED_ARC, UNSET
#best result with AUTOMATIC, GLOBAL_CHEAPEST_ARC, PATH_CHEAPEST_ARC, PATH_MOST_CONSTRAINED_ARC, UNSET
search_parameters.first_solution_strategy = (
    routing_enums_pb2.FirstSolutionStrategy.AUTOMATIC)

# Solve the problem.
solution = routing.SolveWithParameters(search_parameters)

# Print solution on console.
if solution:
    print_solution(manager, routing, solution)


[[  0 362  -1 300 201  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1]
 [362   0 332  -1  -1 142 201  -1  -1 251  -1  -1  -1  -1  -1  -1]
 [ -1 332   0  -1  -1  -1 213 120  -1  -1  -1  -1  -1  -1  -1  -1]
 [300  -1  -1   0 245  -1  -1  -1  -1  -1  -1 263  -1 312  -1  -1]
 [201  -1  -1 245   0 176  -1  -1 112  -1  -1 114  -1  -1  -1  -1]
 [ -1 142  -1  -1 176   0  -1  -1 105  -1  -1  -1  -1  -1  -1  -1]
 [ -1 201 213  -1  -1  -1   0 209  -1 157  -1  -1  -1  -1  -1  -1]
 [ -1  -1 120  -1  -1  -1 209   0  -1  -1 111  -1  -1  -1  -1  -1]
 [ -1  -1  -1  -1 112 105  -1  -1   0 204  -1  -1  95  -1  -1  -1]
 [ -1 251  -1  -1  -1  -1 157  -1 204   0 318  -1 177  -1  -1 244]
 [ -1  -1  -1  -1  -1  -1  -1 111  -1 318   0  -1  -1  -1  -1 205]
 [ -1  -1  -1 263 114  -1  -1  -1  -1  -1  -1   0  86 175  -1  -1]
 [ -1  -1  -1  -1  -1  -1  -1  -1  95 177  -1  86   0  -1 170  -1]
 [ -1  -1  -1 312  -1  -1  -1  -1  -1  -1  -1 175  -1   0 180  -1]
 [ -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1  -1 170 180   0 

In [4]:
#Use CASE : Christos's Greek Yogurt
#https://learning.edx.org/course/course-v1:MITx+CTL.SC0x+2T2020/block-v1:MITx+CTL.SC0x+2T2020+type@sequential+block@7e84b52028df41cd95b7ffef2872d379/block-v1:MITx+CTL.SC0x+2T2020+type@vertical+block@10256a90e6594e3284d9086fcdb0dd14
#Christos's Yogurt is a popular greek yogurt manufacturer in the United States. 
#The company has production facilities in Chicago, Atlanta and Denver.
#Each facility can make only 10000 containers of yogurt per week.
#One of Christos's main customers, Dairy Bucket, has placed a large order.
#Dairy Bucket distributes their order over their 3 facilities located in Boston, Seattle and Tampa.
#Christos wants to minimize his transportation costs while satisfying Dairy Bucket's order.

from ortools.linear_solver import pywraplp
import numpy as np

def create_data_model():
  """Stores the data for the problem."""
  data = {}
  # Shipping Cost (dollars/container)
  #                Boston	Seattle	Tampa
  # Chicago       
  # Atlanta
  # Denver
  data['obj_coeffs'] = [
   [1.04, 1.27, 1.22],
   [1.23, 1.93, 0.60],
   [1.92, 0.94, 1.03]]

  data['constraint_coeffs_min_max'] = [  
      #Dairy Bucket's Demand (containers/week)
      ([[1, 0, 0],
        [1, 0, 0],
        [1, 0, 0]], 11000, 11000),
      ([[0, 1, 0],
        [0, 1, 0],
        [0, 1, 0]], 6300, 6300),        
      ([[0, 0, 1],
        [0, 0, 1],
        [0, 0, 1]], 7400, 7400),
      
     #quantités expédiées

      ([[1, 1, 1],
        [0, 0, 0],
        [0, 0, 0]], 0, 10000),
      ([[0, 0, 0],
        [1, 1, 1],
        [0, 0, 0]], 0, 10000),
      ([[0, 0, 0],
        [0, 0, 0],
        [1, 1, 1]], 0, 10000)  ]

  return data


data = create_data_model()
# Create the mip solver with the SCIP backend.
solver = pywraplp.Solver.CreateSolver('CBC')
infinity = solver.infinity()

x=[[solver.IntVar(0, infinity, f'x[{j},{i}]') for i in range(len(data['obj_coeffs'][j]))] for j in range(len(data['obj_coeffs']))] 

for c in data['constraint_coeffs_min_max']:
  constraint = solver.RowConstraint(c[1], c[2], '')
  for ji,v in np.ndenumerate(c[0]):
    constraint.SetCoefficient(x[ji[0]][ji[1]], v*1.0)
print('Number of constraints =', solver.NumConstraints())
# In Python, you can also set the constraints as follows.
# for i in range(data['num_constraints']):
#  constraint_expr = \
# [data['constraint_coeffs'][i][j] * x[j] for j in range(data['num_vars'])]
#  solver.Add(sum(constraint_expr) <= data['bounds'][i])

objective = solver.Objective()
for ji,v in np.ndenumerate(data['obj_coeffs']):
  objective.SetCoefficient(x[ji[0]][ji[1]], v*1.0)
objective.SetMinimization()
# In Python, you can also set the objective as follows.
# obj_expr = [data['obj_coeffs'][j] * x[j] for j in range(data['num_vars'])]
# solver.Maximize(solver.Sum(obj_expr))

status = solver.Solve()

if status == pywraplp.Solver.OPTIMAL:
  print('Objective value =', solver.Objective().Value())
  for j in x:
    for i in j:
      print(i.name(), ' = ', i.solution_value())
  print()
  print('Problem solved in %f milliseconds' % solver.wall_time())
  print('Problem solved in %d iterations' % solver.iterations())
  print('Problem solved in %d branch-and-bound nodes' % solver.nodes())
else:
  print('The problem does not have an optimal solution.')


Number of constraints = 6
Objective value = 21992.0
x[0,0]  =  10000.0
x[0,1]  =  0.0
x[0,2]  =  0.0
x[1,0]  =  1000.0
x[1,1]  =  0.0
x[1,2]  =  7400.0
x[2,0]  =  0.0
x[2,1]  =  6300.0
x[2,2]  =  0.0

Problem solved in 4.000000 milliseconds
Problem solved in 0 iterations
Problem solved in 0 branch-and-bound nodes
